export const wuku = [
  'Sinta',
  'Landep',
  'Ukir',
  'Kulantir',
  'Tolu',
  'Gumbreg',
  'Wariga',
  'Warigadean',
  'Julungwangi',
  'Sungsang',
  'Dungulan',
  'Kuningan',
  'Langkir',
  'Medangsia',
  'Pujut',
  'Pahang',
  'Krulut',
  'Merakih',
  'Tambir',
  'Medangkungan',
  'Matal',
  'Uye',
  'Menail',
  'Prangbakat',
  'Bala',
  'Ugu',
  'Wayang',
  'Kelawu',
  'Dukut',
  'Watugunung',
] as const
export const ekawara = ['Luang'] as const
export const dwiwara = ['Menga', 'Pepet'] as const
export const triwara = ['Pasah', 'Beteng', 'Kajeng'] as const
export const caturwara = ['Sri', 'Laba', 'Jaya', 'Menala'] as const
export const pancawara = ['Umanis', 'Paing', 'Pon', 'Wage', 'Kliwon'] as const
export const sadwara = [
  'Tungleh',
  'Aryang',
  'Urukung',
  'Paniron',
  'Was',
  'Maulu',
] as const
export const saptawara = [
  'Redite',
  'Soma',
  'Anggara',
  'Buda',
  'Wraspati',
  'Sukra',
  'Saniscara',
] as const
export const astawara = [
  'Sri',
  'Indra',
  'Guru',
  'Yama',
  'Ludra',
  'Brahma',
  'Kala',
  'Uma',
] as const
export const sangawara = [
  'Dangu',
  'Jangur',
  'Gigis',
  'Nohan',
  'Ogan',
  'Erangan',
  'Urungan',
  'Tulus',
  'Dadi',
] as const
export const dasawara = [
  'Pandita',
  'Pati',
  'Suka',
  'Duka',
  'Sri',
  'Manuh',
  'Manusa',
  'Raja',
  'Dewa',
  'Raksasa',
]

export const sasih = [
  'Kasa',
  'Karo',
  'Katiga',
  'Kapat',
  'Kalima',
  'Kanem',
  'Kapitu',
  'Kaulu',
  'Kasanga',
  'Kadasa',
  'Jiestha',
  'Sadha',
] as const

export const penanggalPangelong = ['Penanggal', 'Pangelong'] as const
export const ingkel = ['Wong', 'Sato', 'Mina', 'Manuk', 'Taru', 'Buku'] as const
export const bhetara = [
  'Bhatara Yamadipati',
  'Bhatara Mahadewa',
  'Bhatara Mahayekti',
  'Bhatara Langsur',
  'Bhatara Bayu',
  'Bhatara Candra',
  'Bhatara Asmara',
  'Bhatara Maharesi',
  'Bhatara Sambu',
  'Bhatara Gana',
  'Bhatara Kamajaya',
  'Bhatara Indra',
  'Bhatara Kala',
  'Bhatara Brahma',
  'Bhatara Guritna',
  'Bhatara Tantra',
  'Bhatara Wisnu',
  'Bhatara Surenggana',
  'Bhatara Siwa',
  'Bhatara Basuki',
  'Bhatara Sakri',
  'Bhatara Kuwera',
  'Bhatara Citrayoga',
  'Bhatara Bisma',
  'Bhatara Durga',
  'Bhatara Singajalma',
  'Bhatara Sri',
  'Bhatara Sedana',
  'Bhatara Baruna',
  'Bhatara Anantaboga',
  'Bhatara Yamadipati',
  'Bhatara Mahadewa',
  'Bhatara Mahayekti',
  'Bhatara Langsur',
] as const
